### ISSUE TITLE
virtualenv --system-site-packages ~/tensorflow

### ISSUE THREAD

**Issue by mshahriarinia** [wolffg/tf-tutorial#5]
`$ virtualenv --system-site-packages ~/tensorflow`

```
New python executable in /Users/morteza/tensorflow/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/morteza/tensorflow/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/morteza/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/morteza/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/morteza/tensorflow/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/morteza/tensorflow/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/morteza/anaconda/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Users/morteza/anaconda/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Users/morteza/anaconda/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/Users/morteza/anaconda/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/morteza/anaconda/lib/python2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/morteza/tensorflow/bin/python - setuptools pip wheel failed with error code 1
```

**Comment by mshahriarinia** [comment]
Ended up taking the conda route

```
python --version
conda create -n tensorflow python=2.7
source activate tensorflow
cd ..
mkdir tf
cd tf
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py2-none-any.whl
conda install -c conda-forge tensorflow
```

**Comment by jake17007** [comment]
I just had this issue and found a solution.

If you want to use Virtualenv, you must disable Conda temporarily -- at least while installing Tensorflow.

Comment out the line that adds Conda to your path -- for me it was in ~./bash_profile and looked like `export PATH="/Users/<yourUserName>/anaconda/bin:$PATH`.

Then try running it again.
